function template(locals) {
var jade_debug = [{ lineno: 1, filename: "test/jade/extend.include.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (_t, annoying, complicated, course, interpolations, javascript, link, onlyVar, strings) {
var jade_indent = [];
jade_debug.unshift({ lineno: 0, filename: "test/jade/layout.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/layout.jade" });
buf.push("\n<h1>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 1, filename: jade_debug[0].filename });
buf.push("this is a layout");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/extend.include.jade" });
jade_debug.unshift({ lineno: 3, filename: "test/jade/extend.include.jade" });
buf.push("\n<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "test/jade/extend.include.jade" });
buf.push("" + (jade.escape((jade_interp = _t("this is the blocks content")) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 0, filename: "test/jade/extend.include.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/header.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/header.jade" });
buf.push("\n<header>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "test/jade/header.jade" });
buf.push("\n  <title>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
buf.push("this is a title");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n</header>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "test/jade/attr.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/attr.jade" });
buf.push("\n<button data-default-message=\"Change Password\" data-inflight-message=\"Changing...\" data-success-message=\"Changed!\" disabled=\"disabled\" class=\"btn\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 1, filename: jade_debug[0].filename });
buf.push("Change Password");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/attr.jade" });
buf.push("\n<div data-default-message=\"Change Password\" data-inflight-message=\"Changing...\" data-success-message=\"Changed!\" disabled=\"disabled\" class=\"btn\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: "test/jade/attr.jade" });
buf.push("Change Password");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "test/jade/attr.jade" });
buf.push("\n<attrtest data-default-message=\"this should be wrapped and recorded 1\" data-inflight-message=\"this should be wrapped and recorded 2\" data-success-message=\"this should be wrapped and recorded 3\" data-form-error=\"this should be wrapped and recorded 4\" data-form-correct=\"this should be wrapped and recorded 5\" data-tooltip=\"this should be wrapped and recorded 6\" placeholder=\"this should be wrapped and recorded 7\" title=\"this should not be wrapped\" type=\"this should not be wrapped\" name=\"this should not be wrapped\" id=\"this should not be wrapped\" style=\"this should not be wrapped\" class=\"this should not be wrapped\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</attrtest>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "test/jade/attr.jade" });
buf.push("\n<input type=\"text\" title=\"Your Email Address\" id=\"reset-email\" placeholder=\"Your Email Address\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 29, filename: "test/jade/attr.jade" });
buf.push("\n<input type=\"text\" title=\"Your Email Address\" id=\"reset-email\" placeholder=\"Your Email Address\" class=\"coursera-reset-input\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "test/jade/attr.jade" });
buf.push("<a" + (jade.attr("placeholder", "some " + (link) + ". this should be ignored", true, false)) + ">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 31, filename: "test/jade/attr.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 31, filename: jade_debug[0].filename });
buf.push("testing");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 32, filename: "test/jade/attr.jade" });
buf.push("pipes");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/code.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/code.jade" });
var str1 = _t('str1')
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "test/jade/code.jade" });
var str2 = _t("str2")
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/code.jade" });
var str3 = str1 || _t('"str3"')
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "test/jade/code.jade" });
var str4 = str2 && _t("'str4'")
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "test/jade/code.jade" });
var strMap = {a: _t('a'), b: _t('b'), c: _t('c')}
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "test/jade/code.jade" });
var strArr = [_t('Lorem ipsum dolor elit'), _t('Quo studio Aristophanem?'), _t("Magni enim leges, sed legibus partam")]
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "test/jade/code.jade" });
var ignore = 'this should not be include'
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "test/jade/comment.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/comment.jade" });
buf.push("\n<!--");
jade_debug.unshift({ lineno: 1, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 1, filename: jade_debug[0].filename });
buf.push("p test html comment text");
jade_debug.shift();
jade_debug.shift();
buf.push("\n-->");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "test/jade/comment.jade" });
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "test/jade/complex.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/complex.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "test/jade/complex.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
buf.push("testing");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/complex.jade" });
buf.push("really");
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "test/jade/complex.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push("annoying");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "test/jade/complex.jade" });
buf.push("pipes");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "test/jade/complex.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("with " + (jade.escape((jade_interp = annoying) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "test/jade/complex.jade" });
buf.push("interpolations annoying");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "test/jade/complex.jade" });
buf.push("<a" + (jade.attr("title", course.get('signatureTrackStatus')['signature_track_duration_left'], true, false)) + ">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = course.get('signatureTrackStatus')['signature_track_duration_left']) == null ? '' : jade_interp)) + " left");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "test/jade/simple.jade" });
jade_debug.unshift({ lineno: 1, filename: "test/jade/simple.jade" });
buf.push("\n<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
buf.push("simple string detection");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
buf.push("strings with " + (jade.escape((jade_interp = interpolations) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = strings) == null ? '' : jade_interp)) + " with multiple " + (jade.escape((jade_interp = interpolations) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("strings with " + (jade.escape((jade_interp = javascript.code()) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("strings with " + (jade.escape((jade_interp = complicated + javascript.code("with quoted strings")) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = onlyVar) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("123");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("!!!");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("$100");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("&nbsp; look! there's a trailing space ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: jade_debug[0].filename });
buf.push("&nbsp; look! there's more space  ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push("&nbsp; look! there's a trailing space&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "test/jade/simple.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("&nbsp; look! there's more space&nbsp;&nbsp;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
jade_debug.shift();
jade_debug.shift();
jade_debug.shift();}.call(this,"_t" in locals_for_with?locals_for_with._t:typeof _t!=="undefined"?_t:undefined,"annoying" in locals_for_with?locals_for_with.annoying:typeof annoying!=="undefined"?annoying:undefined,"complicated" in locals_for_with?locals_for_with.complicated:typeof complicated!=="undefined"?complicated:undefined,"course" in locals_for_with?locals_for_with.course:typeof course!=="undefined"?course:undefined,"interpolations" in locals_for_with?locals_for_with.interpolations:typeof interpolations!=="undefined"?interpolations:undefined,"javascript" in locals_for_with?locals_for_with.javascript:typeof javascript!=="undefined"?javascript:undefined,"link" in locals_for_with?locals_for_with.link:typeof link!=="undefined"?link:undefined,"onlyVar" in locals_for_with?locals_for_with.onlyVar:typeof onlyVar!=="undefined"?onlyVar:undefined,"strings" in locals_for_with?locals_for_with.strings:typeof strings!=="undefined"?strings:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "extends layout\nblock content\n  p\n    | #{_t(\"this is the blocks content\")}\n  include includes.jade");
}
}