define({
	"#{course.get('signatureTrackStatus')['signature_track_duration_left']} left": "#{course.get('signatureTrackStatus')['signature_track_duration_left']} left",
	"#{strings} with multiple #{interpolations}": "#{strings} with multiple #{interpolations}",
	"&nbsp; look! there's a trailing space": "&nbsp; look! there's a trailing space",
	"&nbsp; look! there's a trailing space&nbsp;": "&nbsp; look! there's a trailing space&nbsp;",
	"&nbsp; look! there's more space": "&nbsp; look! there's more space",
	"&nbsp; look! there's more space&nbsp;&nbsp;": "&nbsp; look! there's more space&nbsp;&nbsp;",
	"Change Password": "Change Password",
	"Changed!": "Changed!",
	"Changing...": "Changing...",
	"Congratulations! Get your Statement of Accomplishment.": "Congratulations! Get your Statement of Accomplishment.",
	"Congratulations! Get your Verified Certificate.": "Congratulations! Get your Verified Certificate.",
	"Get your grade.": "Get your grade.",
	"Go to class": "Go to class",
	"Grading in progress.": "Grading in progress.",
	"Learn \"for\" Free": "Learn \"for\" Free",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ego quoque, inquit, didicerim libentius si quid attuleris, quam te reprehenderim. Nunc de hominis summo bono quaeritur; Itaque quantum adiit periculum! ad honestatem enim illum omnem conatum suum referebat, non ad voluptatem. Occultum facinus esse potuerit, gaudebit;": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ego quoque, inquit, didicerim libentius si quid attuleris, quam te reprehenderim. Nunc de hominis summo bono quaeritur; Itaque quantum adiit periculum! ad honestatem enim illum omnem conatum suum referebat, non ad voluptatem. Occultum facinus esse potuerit, gaudebit;",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Sed ne, dum huic obsequor, vobis molestus sim. In qua quid est boni praeter summam voluptatem, et eam sempiternam? Nihil sane.": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Sed ne, dum huic obsequor, vobis molestus sim. In qua quid est boni praeter summam voluptatem, et eam sempiternam? Nihil sane.",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum altera prosunt, nocent altera. Conferam avum tuum Drusum cum C. Cur id non ita fit? Duo Reges: constructio interrete. Equidem etiam Epicurum, in physicis quidem, Democriteum puto. At ille non pertimuit saneque fidenter: Istis quidem ipsis verbis, inquit; Scio enim esse quosdam, qui quavis lingua philosophari possint; At enim hic etiam dolore. Scaevolam M.": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quorum altera prosunt, nocent altera. Conferam avum tuum Drusum cum C. Cur id non ita fit? Duo Reges: constructio interrete. Equidem etiam Epicurum, in physicis quidem, Democriteum puto. At ille non pertimuit saneque fidenter: Istis quidem ipsis verbis, inquit; Scio enim esse quosdam, qui quavis lingua philosophari possint; At enim hic etiam dolore. Scaevolam M.",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Scio enim esse quosdam, qui quavis lingua philosophari possint; An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat. Sed ad bona praeterita redeamus. Quis istum dolorem timet?": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Scio enim esse quosdam, qui quavis lingua philosophari possint; An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat. Sed ad bona praeterita redeamus. Quis istum dolorem timet?",
	"This course does not release Statements of Accomplishment.": "This course does not release Statements of Accomplishment.",
	"View class archive": "View class archive",
	"View course record": "View course record",
	"You did not earn a Statement of Accomplishment. Get your grade.": "You did not earn a Statement of Accomplishment. Get your grade.",
	"Your Email Address": "Your Email Address",
	"annoying": "annoying",
	"interpolations annoying": "interpolations annoying",
	"pipes": "pipes",
	"really": "really",
	"simple string detection": "simple string detection",
	"strings with #{complicated + javascript.code(\"with quoted strings\")}": "strings with #{complicated + javascript.code(\"with quoted strings\")}",
	"strings with #{interpolations}": "strings with #{interpolations}",
	"strings with #{javascript.code()}": "strings with #{javascript.code()}",
	"testing": "testing",
	"this should be wrapped and recorded 1": "this should be wrapped and recorded 1",
	"this should be wrapped and recorded 2": "this should be wrapped and recorded 2",
	"this should be wrapped and recorded 3": "this should be wrapped and recorded 3",
	"this should be wrapped and recorded 4": "this should be wrapped and recorded 4",
	"this should be wrapped and recorded 5": "this should be wrapped and recorded 5",
	"this should be wrapped and recorded 6": "this should be wrapped and recorded 6",
	"this should be wrapped and recorded 7": "this should be wrapped and recorded 7",
	"with #{annoying}": "with #{annoying}"
});